// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: status.proto

package protobuf

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastProcessedTick uint32                 `protobuf:"varint,1,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusResponse) GetLastProcessedTick() uint32 {
	if x != nil {
		return x.LastProcessedTick
	}
	return 0
}

type GetHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthCheckResponse) Reset() {
	*x = GetHealthCheckResponse{}
	mi := &file_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthCheckResponse) ProtoMessage() {}

func (x *GetHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*GetHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetSkippedTicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkippedTicks  []uint32               `protobuf:"varint,1,rep,packed,name=skipped_ticks,json=skippedTicks,proto3" json:"skipped_ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkippedTicksResponse) Reset() {
	*x = GetSkippedTicksResponse{}
	mi := &file_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkippedTicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkippedTicksResponse) ProtoMessage() {}

func (x *GetSkippedTicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkippedTicksResponse.ProtoReflect.Descriptor instead.
func (*GetSkippedTicksResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{2}
}

func (x *GetSkippedTicksResponse) GetSkippedTicks() []uint32 {
	if x != nil {
		return x.SkippedTicks
	}
	return nil
}

type TickInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	FirstTick     uint32                 `protobuf:"varint,2,opt,name=first_tick,json=firstTick,proto3" json:"first_tick,omitempty"`
	LastTick      uint32                 `protobuf:"varint,3,opt,name=last_tick,json=lastTick,proto3" json:"last_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickInterval) Reset() {
	*x = TickInterval{}
	mi := &file_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickInterval) ProtoMessage() {}

func (x *TickInterval) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickInterval.ProtoReflect.Descriptor instead.
func (*TickInterval) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{3}
}

func (x *TickInterval) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TickInterval) GetFirstTick() uint32 {
	if x != nil {
		return x.FirstTick
	}
	return 0
}

func (x *TickInterval) GetLastTick() uint32 {
	if x != nil {
		return x.LastTick
	}
	return 0
}

type GetTickIntervalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intervals     []*TickInterval        `protobuf:"bytes,1,rep,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickIntervalsResponse) Reset() {
	*x = GetTickIntervalsResponse{}
	mi := &file_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickIntervalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickIntervalsResponse) ProtoMessage() {}

func (x *GetTickIntervalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickIntervalsResponse.ProtoReflect.Descriptor instead.
func (*GetTickIntervalsResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{4}
}

func (x *GetTickIntervalsResponse) GetIntervals() []*TickInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

// start of archiver compatible status response
type GetArchiverStatusResponse struct {
	state                          protoimpl.MessageState            `protogen:"open.v1"`
	LastProcessedTick              *ProcessedTick                    `protobuf:"bytes,1,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	LastProcessedTicksPerEpoch     map[uint32]uint32                 `protobuf:"bytes,2,rep,name=last_processed_ticks_per_epoch,json=lastProcessedTicksPerEpoch,proto3" json:"last_processed_ticks_per_epoch,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkippedTicks                   []*SkippedTicksInterval           `protobuf:"bytes,3,rep,name=skipped_ticks,json=skippedTicks,proto3" json:"skipped_ticks,omitempty"`
	ProcessedTickIntervalsPerEpoch []*ProcessedTickIntervalsPerEpoch `protobuf:"bytes,4,rep,name=processed_tick_intervals_per_epoch,json=processedTickIntervalsPerEpoch,proto3" json:"processed_tick_intervals_per_epoch,omitempty"`
	EmptyTicksPerEpoch             map[uint32]uint32                 `protobuf:"bytes,5,rep,name=empty_ticks_per_epoch,json=emptyTicksPerEpoch,proto3" json:"empty_ticks_per_epoch,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetArchiverStatusResponse) Reset() {
	*x = GetArchiverStatusResponse{}
	mi := &file_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchiverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchiverStatusResponse) ProtoMessage() {}

func (x *GetArchiverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchiverStatusResponse.ProtoReflect.Descriptor instead.
func (*GetArchiverStatusResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{5}
}

func (x *GetArchiverStatusResponse) GetLastProcessedTick() *ProcessedTick {
	if x != nil {
		return x.LastProcessedTick
	}
	return nil
}

func (x *GetArchiverStatusResponse) GetLastProcessedTicksPerEpoch() map[uint32]uint32 {
	if x != nil {
		return x.LastProcessedTicksPerEpoch
	}
	return nil
}

func (x *GetArchiverStatusResponse) GetSkippedTicks() []*SkippedTicksInterval {
	if x != nil {
		return x.SkippedTicks
	}
	return nil
}

func (x *GetArchiverStatusResponse) GetProcessedTickIntervalsPerEpoch() []*ProcessedTickIntervalsPerEpoch {
	if x != nil {
		return x.ProcessedTickIntervalsPerEpoch
	}
	return nil
}

func (x *GetArchiverStatusResponse) GetEmptyTicksPerEpoch() map[uint32]uint32 {
	if x != nil {
		return x.EmptyTicksPerEpoch
	}
	return nil
}

type ProcessedTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickNumber    uint32                 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedTick) Reset() {
	*x = ProcessedTick{}
	mi := &file_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTick) ProtoMessage() {}

func (x *ProcessedTick) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTick.ProtoReflect.Descriptor instead.
func (*ProcessedTick) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessedTick) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *ProcessedTick) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ProcessedTickInterval struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InitialProcessedTick uint32                 `protobuf:"varint,1,opt,name=initial_processed_tick,json=initialProcessedTick,proto3" json:"initial_processed_tick,omitempty"`
	LastProcessedTick    uint32                 `protobuf:"varint,2,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessedTickInterval) Reset() {
	*x = ProcessedTickInterval{}
	mi := &file_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTickInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTickInterval) ProtoMessage() {}

func (x *ProcessedTickInterval) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTickInterval.ProtoReflect.Descriptor instead.
func (*ProcessedTickInterval) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessedTickInterval) GetInitialProcessedTick() uint32 {
	if x != nil {
		return x.InitialProcessedTick
	}
	return 0
}

func (x *ProcessedTickInterval) GetLastProcessedTick() uint32 {
	if x != nil {
		return x.LastProcessedTick
	}
	return 0
}

type ProcessedTickIntervalsPerEpoch struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Epoch         uint32                   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Intervals     []*ProcessedTickInterval `protobuf:"bytes,2,rep,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedTickIntervalsPerEpoch) Reset() {
	*x = ProcessedTickIntervalsPerEpoch{}
	mi := &file_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTickIntervalsPerEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTickIntervalsPerEpoch) ProtoMessage() {}

func (x *ProcessedTickIntervalsPerEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTickIntervalsPerEpoch.ProtoReflect.Descriptor instead.
func (*ProcessedTickIntervalsPerEpoch) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessedTickIntervalsPerEpoch) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ProcessedTickIntervalsPerEpoch) GetIntervals() []*ProcessedTickInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

type SkippedTicksInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTick     uint32                 `protobuf:"varint,1,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	EndTick       uint32                 `protobuf:"varint,2,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedTicksInterval) Reset() {
	*x = SkippedTicksInterval{}
	mi := &file_status_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedTicksInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedTicksInterval) ProtoMessage() {}

func (x *SkippedTicksInterval) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedTicksInterval.ProtoReflect.Descriptor instead.
func (*SkippedTicksInterval) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{9}
}

func (x *SkippedTicksInterval) GetStartTick() uint32 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *SkippedTicksInterval) GetEndTick() uint32 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

type SkippedTicksIntervalList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SkippedTicks  []*SkippedTicksInterval `protobuf:"bytes,1,rep,name=skipped_ticks,json=skippedTicks,proto3" json:"skipped_ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedTicksIntervalList) Reset() {
	*x = SkippedTicksIntervalList{}
	mi := &file_status_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedTicksIntervalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedTicksIntervalList) ProtoMessage() {}

func (x *SkippedTicksIntervalList) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedTicksIntervalList.ProtoReflect.Descriptor instead.
func (*SkippedTicksIntervalList) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{10}
}

func (x *SkippedTicksIntervalList) GetSkippedTicks() []*SkippedTicksInterval {
	if x != nil {
		return x.SkippedTicks
	}
	return nil
}

var File_status_proto protoreflect.FileDescriptor

const file_status_proto_rawDesc = "" +
	"\n" +
	"\fstatus.proto\x12\x11status.service.pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x11GetStatusResponse\x12.\n" +
	"\x13last_processed_tick\x18\x01 \x01(\rR\x11lastProcessedTick\"0\n" +
	"\x16GetHealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\">\n" +
	"\x17GetSkippedTicksResponse\x12#\n" +
	"\rskipped_ticks\x18\x01 \x03(\rR\fskippedTicks\"`\n" +
	"\fTickInterval\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12\x1d\n" +
	"\n" +
	"first_tick\x18\x02 \x01(\rR\tfirstTick\x12\x1b\n" +
	"\tlast_tick\x18\x03 \x01(\rR\blastTick\"Y\n" +
	"\x18GetTickIntervalsResponse\x12=\n" +
	"\tintervals\x18\x01 \x03(\v2\x1f.status.service.pb.TickIntervalR\tintervals\"\xdc\x05\n" +
	"\x19GetArchiverStatusResponse\x12P\n" +
	"\x13last_processed_tick\x18\x01 \x01(\v2 .status.service.pb.ProcessedTickR\x11lastProcessedTick\x12\x90\x01\n" +
	"\x1elast_processed_ticks_per_epoch\x18\x02 \x03(\v2L.status.service.pb.GetArchiverStatusResponse.LastProcessedTicksPerEpochEntryR\x1alastProcessedTicksPerEpoch\x12L\n" +
	"\rskipped_ticks\x18\x03 \x03(\v2'.status.service.pb.SkippedTicksIntervalR\fskippedTicks\x12}\n" +
	"\"processed_tick_intervals_per_epoch\x18\x04 \x03(\v21.status.service.pb.ProcessedTickIntervalsPerEpochR\x1eprocessedTickIntervalsPerEpoch\x12w\n" +
	"\x15empty_ticks_per_epoch\x18\x05 \x03(\v2D.status.service.pb.GetArchiverStatusResponse.EmptyTicksPerEpochEntryR\x12emptyTicksPerEpoch\x1aM\n" +
	"\x1fLastProcessedTicksPerEpochEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aE\n" +
	"\x17EmptyTicksPerEpochEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"F\n" +
	"\rProcessedTick\x12\x1f\n" +
	"\vtick_number\x18\x01 \x01(\rR\n" +
	"tickNumber\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\"}\n" +
	"\x15ProcessedTickInterval\x124\n" +
	"\x16initial_processed_tick\x18\x01 \x01(\rR\x14initialProcessedTick\x12.\n" +
	"\x13last_processed_tick\x18\x02 \x01(\rR\x11lastProcessedTick\"~\n" +
	"\x1eProcessedTickIntervalsPerEpoch\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12F\n" +
	"\tintervals\x18\x02 \x03(\v2(.status.service.pb.ProcessedTickIntervalR\tintervals\"P\n" +
	"\x14SkippedTicksInterval\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x01 \x01(\rR\tstartTick\x12\x19\n" +
	"\bend_tick\x18\x02 \x01(\rR\aendTick\"h\n" +
	"\x18SkippedTicksIntervalList\x12L\n" +
	"\rskipped_ticks\x18\x01 \x03(\v2'.status.service.pb.SkippedTicksIntervalR\fskippedTicks2\xb9\x04\n" +
	"\rStatusService\x12r\n" +
	"\x10GetTickIntervals\x12\x16.google.protobuf.Empty\x1a+.status.service.pb.GetTickIntervalsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/tickIntervals\x12u\n" +
	"\x11GetArchiverStatus\x12\x16.google.protobuf.Empty\x1a,.status.service.pb.GetArchiverStatusResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/archiverStatus\x12x\n" +
	"\x18GetErroneousSkippedTicks\x12\x16.google.protobuf.Empty\x1a*.status.service.pb.GetSkippedTicksResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/skippedTicks\x12]\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a$.status.service.pb.GetStatusResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/status\x12d\n" +
	"\x0eGetHealthCheck\x12\x16.google.protobuf.Empty\x1a).status.service.pb.GetHealthCheckResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB=Z;github.com/qubic/go-data-publisher/status-service/protobuf/b\x06proto3"

var (
	file_status_proto_rawDescOnce sync.Once
	file_status_proto_rawDescData []byte
)

func file_status_proto_rawDescGZIP() []byte {
	file_status_proto_rawDescOnce.Do(func() {
		file_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)))
	})
	return file_status_proto_rawDescData
}

var file_status_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_status_proto_goTypes = []any{
	(*GetStatusResponse)(nil),              // 0: status.service.pb.GetStatusResponse
	(*GetHealthCheckResponse)(nil),         // 1: status.service.pb.GetHealthCheckResponse
	(*GetSkippedTicksResponse)(nil),        // 2: status.service.pb.GetSkippedTicksResponse
	(*TickInterval)(nil),                   // 3: status.service.pb.TickInterval
	(*GetTickIntervalsResponse)(nil),       // 4: status.service.pb.GetTickIntervalsResponse
	(*GetArchiverStatusResponse)(nil),      // 5: status.service.pb.GetArchiverStatusResponse
	(*ProcessedTick)(nil),                  // 6: status.service.pb.ProcessedTick
	(*ProcessedTickInterval)(nil),          // 7: status.service.pb.ProcessedTickInterval
	(*ProcessedTickIntervalsPerEpoch)(nil), // 8: status.service.pb.ProcessedTickIntervalsPerEpoch
	(*SkippedTicksInterval)(nil),           // 9: status.service.pb.SkippedTicksInterval
	(*SkippedTicksIntervalList)(nil),       // 10: status.service.pb.SkippedTicksIntervalList
	nil,                                    // 11: status.service.pb.GetArchiverStatusResponse.LastProcessedTicksPerEpochEntry
	nil,                                    // 12: status.service.pb.GetArchiverStatusResponse.EmptyTicksPerEpochEntry
	(*emptypb.Empty)(nil),                  // 13: google.protobuf.Empty
}
var file_status_proto_depIdxs = []int32{
	3,  // 0: status.service.pb.GetTickIntervalsResponse.intervals:type_name -> status.service.pb.TickInterval
	6,  // 1: status.service.pb.GetArchiverStatusResponse.last_processed_tick:type_name -> status.service.pb.ProcessedTick
	11, // 2: status.service.pb.GetArchiverStatusResponse.last_processed_ticks_per_epoch:type_name -> status.service.pb.GetArchiverStatusResponse.LastProcessedTicksPerEpochEntry
	9,  // 3: status.service.pb.GetArchiverStatusResponse.skipped_ticks:type_name -> status.service.pb.SkippedTicksInterval
	8,  // 4: status.service.pb.GetArchiverStatusResponse.processed_tick_intervals_per_epoch:type_name -> status.service.pb.ProcessedTickIntervalsPerEpoch
	12, // 5: status.service.pb.GetArchiverStatusResponse.empty_ticks_per_epoch:type_name -> status.service.pb.GetArchiverStatusResponse.EmptyTicksPerEpochEntry
	7,  // 6: status.service.pb.ProcessedTickIntervalsPerEpoch.intervals:type_name -> status.service.pb.ProcessedTickInterval
	9,  // 7: status.service.pb.SkippedTicksIntervalList.skipped_ticks:type_name -> status.service.pb.SkippedTicksInterval
	13, // 8: status.service.pb.StatusService.GetTickIntervals:input_type -> google.protobuf.Empty
	13, // 9: status.service.pb.StatusService.GetArchiverStatus:input_type -> google.protobuf.Empty
	13, // 10: status.service.pb.StatusService.GetErroneousSkippedTicks:input_type -> google.protobuf.Empty
	13, // 11: status.service.pb.StatusService.GetStatus:input_type -> google.protobuf.Empty
	13, // 12: status.service.pb.StatusService.GetHealthCheck:input_type -> google.protobuf.Empty
	4,  // 13: status.service.pb.StatusService.GetTickIntervals:output_type -> status.service.pb.GetTickIntervalsResponse
	5,  // 14: status.service.pb.StatusService.GetArchiverStatus:output_type -> status.service.pb.GetArchiverStatusResponse
	2,  // 15: status.service.pb.StatusService.GetErroneousSkippedTicks:output_type -> status.service.pb.GetSkippedTicksResponse
	0,  // 16: status.service.pb.StatusService.GetStatus:output_type -> status.service.pb.GetStatusResponse
	1,  // 17: status.service.pb.StatusService.GetHealthCheck:output_type -> status.service.pb.GetHealthCheckResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_status_proto_init() }
func file_status_proto_init() {
	if File_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_proto_goTypes,
		DependencyIndexes: file_status_proto_depIdxs,
		MessageInfos:      file_status_proto_msgTypes,
	}.Build()
	File_status_proto = out.File
	file_status_proto_goTypes = nil
	file_status_proto_depIdxs = nil
}
