services:
  qubic-transactions-producer:
    image: ghcr.io/qubic/transactions-producer:latest
    container_name: qubic-transactions-producer
    ports:
      - "127.0.0.1:9994:9999"
    environment:
      QUBIC_TRANSACTIONS_PUBLISHER_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092" # set kafka url here
      QUBIC_TRANSACTIONS_PUBLISHER_KAFKA_TX_TOPIC: "qubic-transactions-test" # set correct topic
      QUBIC_TRANSACTIONS_PUBLISHER_ARCHIVER_GRPC_HOST: "qubic-archiver:8001"
      QUBIC_TRANSACTIONS_PUBLISHER_NR_WORKERS: 10
      QUBIC_TRANSACTIONS_PUBLISHER_ARCHIVER_READ_TIMEOUT: 1m
    volumes:
      - ./store:/app/store
    networks:
      - qubic
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://127.0.0.1:9999/v1/status" ]
      interval: 15s
      timeout: 3s
      retries: 3
    restart: always
networks:
  qubic: