name: Create tick data publisher image

on:
  push:
    branches:
      - feature/archiver-v2-compat

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tick-data-publisher
          file: ./tick-data-publisher/Dockerfile
          push: true
          tags: ghcr.io/qubic/tick-data-publisher:snapshot