on:
  push:
    paths:
      - 'transactions-consumer/**'
  pull_request:
    paths:
      - 'transactions-consumer/**'

name: Test transactions consumer
jobs:
  test-nocache:
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: go test -p 1 -tags ci ./...
        working-directory: transactions-consumer